### ISSUE TITLE
print_level not printing error value

### ISSUE THREAD

**Issue by stepeos** [kthohr/optim#64]
Expected behavior:
Just like the docs, the error function should print error value.
```
    int print_level: Set print level.

        Level 1: Print iteration count and error value.

        Level 2: Level 1 and print best input values and corresponding objective function value.

        Level 3: Level 2 and print full population matrix, XX.
```
Level one says, that the error value is printed.

Actual Behavior:
The rel_objfn_change is printed.
I think the best objective function (my understand of error value) is far more reasonable to print, no?

**Comment by kthohr** [comment]
Thanks for flagging. (A bit unclear from your report, but I assume you are referring to the DE/PSO algorithms.)

I've updated the docs to be a little clearer on this. What matters for "convergence" is the change in objective function value between iterations, rather than the absolute value of the objective function, though the latter can be seen at level 2.
